### ISSUE TITLE
NewTable breaks addons that use setmetatable

### ISSUE THREAD

**Issue by Driphter** [alarofrunetotem/LibInit#1]
As of version 40, addons such as GarrisonCommander that use setmetatable on tables returned by NewTable are breaking.

**Comment by alarofrunetotem** [comment]
Thank you for raising this issue
GarrisonCommander is being updated for LibInit 40 (current beta) (same author sa LibInit, i.e. me :) )
I was not aware of anyone using LibInit but me, so I was maybe too much liberal in breaking backward compatibility.
Are you using it or you just downloaded it as a stand alone Library?

**Comment by Driphter** [comment]
Ah, I'm not using it myself. I just like using standalone libraries so I have the "latest and greatest". Thanks for GarrisonCommander, btw :)

**Comment by alarofrunetotem** [comment]
I see.
I updated both GarrisonCommander and OrderHallCommander to use LibInit 41

**Comment by alarofrunetotem** [comment]
Fixed with release 41
